#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 13, 2018 11:28:07 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import studentproject_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    studentproject_support.set_Tk_var()
    top = New_Toplevel (root)
    studentproject_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    studentproject_support.set_Tk_var()
    top = New_Toplevel (w)
    studentproject_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 16 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x554+451+96")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.15, rely=0.11, relheight=0.51, relwidth=0.68)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=405)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.2, rely=0.14, height=21, width=64)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Name''')
        self.Label1.configure(width=64)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.2, rely=0.32, height=21, width=74)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Roll No''')
        self.Label2.configure(width=74)

        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.22, rely=0.49, height=21, width=54)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font9)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Marks''')
        self.Label3.configure(width=54)

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.22, rely=0.67, height=21, width=54)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font9)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Sex''')
        self.Label4.configure(width=54)

        self.Label5 = Label(self.Frame1)
        self.Label5.place(relx=0.25, rely=0.81, height=31, width=44)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font9)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Age''')
        self.Label5.configure(width=44)

        self.txtName = Text(self.Frame1)
        self.txtName.place(relx=0.59, rely=0.14, relheight=0.08, relwidth=0.33)
        self.txtName.configure(background="white")
        self.txtName.configure(font="TkTextFont")
        self.txtName.configure(foreground="black")
        self.txtName.configure(highlightbackground="#d9d9d9")
        self.txtName.configure(highlightcolor="black")
        self.txtName.configure(insertbackground="black")
        self.txtName.configure(selectbackground="#c4c4c4")
        self.txtName.configure(selectforeground="black")
        self.txtName.configure(width=134)
        self.txtName.configure(wrap=WORD)

        self.txtRoll = Text(self.Frame1)
        self.txtRoll.place(relx=0.59, rely=0.32, relheight=0.08, relwidth=0.33)
        self.txtRoll.configure(background="white")
        self.txtRoll.configure(font="TkTextFont")
        self.txtRoll.configure(foreground="black")
        self.txtRoll.configure(highlightbackground="#d9d9d9")
        self.txtRoll.configure(highlightcolor="black")
        self.txtRoll.configure(insertbackground="black")
        self.txtRoll.configure(selectbackground="#c4c4c4")
        self.txtRoll.configure(selectforeground="black")
        self.txtRoll.configure(width=134)
        self.txtRoll.configure(wrap=WORD)

        self.txtMarks = Text(self.Frame1)
        self.txtMarks.place(relx=0.59, rely=0.49, relheight=0.08, relwidth=0.33)
        self.txtMarks.configure(background="white")
        self.txtMarks.configure(font="TkTextFont")
        self.txtMarks.configure(foreground="black")
        self.txtMarks.configure(highlightbackground="#d9d9d9")
        self.txtMarks.configure(highlightcolor="black")
        self.txtMarks.configure(insertbackground="black")
        self.txtMarks.configure(selectbackground="#c4c4c4")
        self.txtMarks.configure(selectforeground="black")
        self.txtMarks.configure(width=134)
        self.txtMarks.configure(wrap=WORD)

        self.Frame2 = Frame(self.Frame1)
        self.Frame2.place(relx=0.59, rely=0.67, relheight=0.09, relwidth=0.38)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=155)

        self.Radiobutton1 = Radiobutton(self.Frame2)
        self.Radiobutton1.place(relx=1.55, rely=2.0, relheight=1.0
                , relwidth=0.37)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''Radio''')

        self.Radiobutton2 = Radiobutton(self.Frame2)
        self.Radiobutton2.place(relx=0.52, rely=0.0, relheight=1.0
                , relwidth=0.43)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''Female''')

        self.Radiobutton3 = Radiobutton(self.Frame2)
        self.Radiobutton3.place(relx=0.06, rely=0.0, relheight=1.0
                , relwidth=0.35)
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify=LEFT)
        self.Radiobutton3.configure(text='''Male''')

        self.Spinbox1 = Spinbox(self.Frame1, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.59, rely=0.84, relheight=0.07, relwidth=0.36)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(from_="1.0")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(selectforeground="black")
        self.Spinbox1.configure(textvariable=studentproject_support.spinbox)
        self.Spinbox1.configure(to="100.0")
        self.Spinbox1.configure(width=145)

        self.btnAdd = Button(top)
        self.btnAdd.place(relx=0.37, rely=0.67, height=24, width=53)
        self.btnAdd.configure(activebackground="#d9d9d9")
        self.btnAdd.configure(activeforeground="#000000")
        self.btnAdd.configure(background="#d9d9d9")
        self.btnAdd.configure(disabledforeground="#a3a3a3")
        self.btnAdd.configure(foreground="#000000")
        self.btnAdd.configure(highlightbackground="#d9d9d9")
        self.btnAdd.configure(highlightcolor="black")
        self.btnAdd.configure(pady="0")
        self.btnAdd.configure(text='''Add''')
        self.btnAdd.configure(width=53)

        self.btnModify = Button(top)
        self.btnModify.place(relx=0.55, rely=0.67, height=24, width=49)
        self.btnModify.configure(activebackground="#d9d9d9")
        self.btnModify.configure(activeforeground="#000000")
        self.btnModify.configure(background="#d9d9d9")
        self.btnModify.configure(disabledforeground="#a3a3a3")
        self.btnModify.configure(foreground="#000000")
        self.btnModify.configure(highlightbackground="#d9d9d9")
        self.btnModify.configure(highlightcolor="black")
        self.btnModify.configure(pady="0")
        self.btnModify.configure(text='''Modify''')

        self.btnShow = Button(top)
        self.btnShow.place(relx=0.18, rely=0.67, height=24, width=50)
        self.btnShow.configure(activebackground="#d9d9d9")
        self.btnShow.configure(activeforeground="#000000")
        self.btnShow.configure(background="#d9d9d9")
        self.btnShow.configure(disabledforeground="#a3a3a3")
        self.btnShow.configure(foreground="#000000")
        self.btnShow.configure(highlightbackground="#d9d9d9")
        self.btnShow.configure(highlightcolor="black")
        self.btnShow.configure(pady="0")
        self.btnShow.configure(text='''Show''')
        self.btnShow.configure(width=50)

        self.btnDelete = Button(top)
        self.btnDelete.place(relx=0.73, rely=0.67, height=24, width=54)
        self.btnDelete.configure(activebackground="#d9d9d9")
        self.btnDelete.configure(activeforeground="#000000")
        self.btnDelete.configure(background="#d9d9d9")
        self.btnDelete.configure(disabledforeground="#a3a3a3")
        self.btnDelete.configure(foreground="#000000")
        self.btnDelete.configure(highlightbackground="#d9d9d9")
        self.btnDelete.configure(highlightcolor="black")
        self.btnDelete.configure(pady="0")
        self.btnDelete.configure(text='''Delete''')
        self.btnDelete.configure(width=54)

        self.lstStudent = Listbox(top)
        self.lstStudent.place(relx=0.18, rely=0.76, relheight=0.22
                , relwidth=0.77)
        self.lstStudent.configure(background="white")
        self.lstStudent.configure(disabledforeground="#a3a3a3")
        self.lstStudent.configure(font="TkFixedFont")
        self.lstStudent.configure(foreground="#000000")
        self.lstStudent.configure(width=464)






if __name__ == '__main__':
    vp_start_gui()



